Add LWC post from WIPDeveloper.com to learning.html
Confirm4Crit/awesome-lwc pull request #13
Opened 2020-10-01 23:13 UTC by BrettMN

2020-10-01 23:55 UTC, gdoenlen requested changes

2020-10-01 23:55 UTC, gdoenlen commented on src/modules/my/learning/learning.html
> +                        <a href="https://wipdeveloper.com/tags/lwc/"
Formatting is pretty borked.

2020-10-02 14:00 UTC, gdoenlen commented on src/modules/my/learning/learning.html
> +                        <a href="https://wipdeveloper.com/tags/lwc/"
I just noticed this is how @Confirm4Crit had formatted this file.

2020-10-02 15:22 UTC, Confirm4Crit approved these changes

2020-10-02 15:26 UTC, merged